name: Security CI (Bandit)

on: [push, pull_request] # workflow запускается при пуше или открытии/обновлении Pull Request

jobs:
  bandit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # проверка репозитория

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11 # установка Python

      - name: Install dependencies
        run: |
          pip install bandit # установка Bandit

      - name: Run Bandit and fail on high
        run: |
          bandit -r . -lll -iii -f json -o bandit.json || true # запуск Bandit рекурсивно по всей директории, JSON в bandit.json
          python - <<'PYCODE'
import json, sys
with open("bandit.json") as f:
    data = json.load(f)
issues = data.get("results", [])
highs = [i for i in issues if str(i.get("issue_severity", "")).upper() == "HIGH"]
if highs:
    sys.exit(1)
else:
    sys.exit(0)
PYCODE
# проверка JSON: если есть хотя бы одна критическая уязвимость - падение
